export const SET_VIDEO = 'SET_VIDEO'

export const SET_VIDEO_LIST = 'SET_VIDEO_LIST'

export const SET_RECOMMEND_VIDEO_LIST = 'SET_RECOMMEND_VIDEO_LIST'

export const SET_ANALYSIS_LIST = 'SET_ANALYSIS_LIST'
